language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

cache:
  directories:
    - node_modules
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/apache-solr-3.6.2
    - $TRAVIS_BUILD_DIR/apache-solr-3.6.2.tgz

php:
  - 5.5

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_script:
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - bash bin/install-solr.sh
  - npm -g install grunt-cli
  - npm install
  - grunt

script: phpunit

# Comment: fake build
