sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

cache:
  directories:
    - node_modules
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/apache-solr-3.6.2
    - $TRAVIS_BUILD_DIR/apache-solr-3.6.2.tgz

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=nightly
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.4
      env: WP_TRAVISCI=phpcs
    - php: 7.3
      env: WP_TRAVISCI=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=4.8

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi
  - bash bin/install-solr.sh
  - npm -g install grunt-cli
  - npm install
  - grunt

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      composer test
      WP_MULTISITE=1 composer test
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer lint
    fi
